services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-dual-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: delfos-fastapi:latest
    container_name: delfos-fastapi
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_SOURCE_NAME: source
      DB_TARGET_NAME: target
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:


